class APIError extends Error {
    constructor(message) {
        super(message);
        this.name = "APIError";
    }

    static MISSING_REQUIRED_VALUES = new APIError("MISSING_REQUIRED_VALUES");
    static LECTURER_ALREADY_EXISTS = new APIError("LECTURER_ALREADY_EXISTS");
    static LECTURER_NOT_FOUND = new APIError("LECTURER_NOT_FOUND");
    static USERNAME_DOESNT_MEET_MINIMAL_REQUIREMENTS = new APIError("USERNAME_DOESNT_MEET_MINIMAL_REQUIREMENTS");
    static USERNAME_DOESNT_MEET_MAXIMAL_REQUIREMENTS = new APIError("USERNAME_DOESNT_MEET_MAXIMAL_REQUIREMENTS");
    static INVALID_CREDENTIALS = new APIError("INVALID_CREDENTIALS");
    static INVALID_VALUE_TYPE = new APIError("INVALID_VALUE_TYPE");
    static INVALID_DATES = new APIError("INVALID_DATES");
    static INVALID_EMAIL = new APIError("INVALID_EMAIL");
    static INVALID_PHONE_NUMBER = new APIError("INVALID_PHONE_NUMBER");
    static RESERVATION_NOT_FOUND = new APIError("RESERVATION_NOT_FOUND");
    static TIME_SLOT_NOT_AVAILABLE = new APIError("TIME_SLOT_NOT_AVAILABLE");
    static TIME_CONFLICT = new APIError("TIME_CONFLICT");
}

module.exports = {
    APIError
}