version: "3.8"

services:
  webserver:
    container_name: webserver
    build: "."
    ports:
      - 3000:3000
    volumes:
      - "./src:/app"
      - "./data:/app/data"
    env_file:
      - .env
    restart: unless-stopped